sudo: required
service:
  - docker

before_install:
  - docker build -t bartekwas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bartekwas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-docker-react"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_ACCESS_KEY
  secret_access_key: $aws_SECRET_KEY  